server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8101
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: /tmp/log/services/panacea/access.log
        archivedLogFilenamePattern: /tmp/log/services/panacea/access-%d.log.gz
        archivedFileCount: 5

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /tmp/log/services/panacea/services.log
      archivedLogFilenamePattern: /tmp/log/services/panacea/services-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
